apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: partner-catalog-ady8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: partner-catalog-ady8
    app.kubernetes.io/part-of: partner-catalog-5
  name: partner-catalog-ady8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: partner-catalog-ady8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: partner-catalog-ady8
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mramdani-tenant/partner-catalog-5/partner-catalog-ady8@sha256:61150a1923ed3fa5da8609e8385d7bb061b47a141a8f7c50b750215bc3280516
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
