apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-ady8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mramdani-tenant/partner-catalog-5/partner-catalog-ady8@sha256:61150a1923ed3fa5da8609e8385d7bb061b47a141a8f7c50b750215bc3280516
        name: my-java-springboot
        resources: {}
status: {}
